### ISSUE TITLE
dashboard present error 

### ISSUE THREAD

**Issue by vdministrator** [robcowart/synesis_lite_suricata#13]
I used elk7.1 and Kibana dashboard present lot of error  after installed synesis_lite_suricata(7.1.x) 
.how can I do resolve this problem ?
![image](https://user-images.githubusercontent.com/12219743/65259917-134d5f00-db38-11e9-853e-e4e19542bde9.png)

![image](https://user-images.githubusercontent.com/12219743/65259888-029ce900-db38-11e9-9c22-e86d51edba7f.png)

![image](https://user-images.githubusercontent.com/12219743/65259825-e4cf8400-db37-11e9-9cd0-baef60b2ecd5.png)

**Comment by ounibassem** [comment]
you can help me !!!

**Comment by ipworkx** [comment]
Hi,
This is related to the fact that your index pattern or data is mapped to the wrong template. Probably the default logstash template which is automaticaly created.
Check your logstash pipeline is using the right template and check that is is loaded/installed correctly.
If it does, delete the index data and start over again.
If it doesn't work. Do this:

Stop logstash
Delete the index pattern and the corresponding data (index)
Import the NDJSON again including the index pattern
start logstash again
You should be fine now

Regards

**Comment by ipworkx** [comment]
You could also checkout if there are any mapping conflicts

**Comment by ounibassem** [comment]
does version 5.x of suricata work with this project! I use Suricata 5 but the problem persists, I delete and add the index, but same problem

**Comment by ounibassem** [comment]
how to resolve mapping conflicts, sometimes I find conflict errors

**Comment by robcowart** [comment]
This has not been updated for any Suricata version after 4.x. As I have moved away from Logstash for such projects, I am not planning to update this project. Sorry.
