### ISSUE TITLE
Kibana Url Format filters appear as raw HTML in saved search visualizations

### ISSUE THREAD

**Issue by ricferr** [robcowart/synesis_lite_suricata#14]
Hello.

In Elasticsearch/KIbana 7.4.0, all saved search visualizations present the Url formats as raw HTML.
They are presented correctly when viewing the same saved search in Discovery.

This did not happen in 6.x.
I have upgraded to 1.1.0 as required for 7.x support.

Screenshots included.

![image](https://user-images.githubusercontent.com/5982853/68121921-09719680-ff01-11e9-8125-c8042cd35df0.png)

![image](https://user-images.githubusercontent.com/5982853/68121989-39209e80-ff01-11e9-88f3-c7c7e228a9a8.png)

Is this a known issue ?
Is there a workaround ?

Thank you.

**Comment by robcowart** [comment]
Can you test with 7.4.2? There were field formatter fixes in 7.4.2.

https://www.elastic.co/guide/en/kibana/7.4/release-notes-7.4.2.html

If it is still an issue, you will need to open a Kibana issue.

**Comment by ricferr** [comment]
Hello again.

You were right. 7.4.2 fixes it. I'm closing the issue.
Thank you.
