### ISSUE TITLE
Converting the synlite_suricata.kibana.7.1.x.json to ndson and import failed in 7.9.1

### ISSUE THREAD

**Issue by Sheltant** [robcowart/synesis_lite_suricata#27]
Hello Robcowart,

You have the latest ndson of synlite_suricata.kibana. ?

Regards,

Sheltan

**Comment by robcowart** [comment]
The last version of the Elastic Stack supported by this solution is 7.1.x. As I am moving away from Logstash, this solution will likely not be updated. Sorry.
