### ISSUE TITLE
Synlite lite suricata install valididity

### ISSUE THREAD

**Issue by NPascar** [robcowart/synesis_lite_suricata#30]
Good Day Mr. Rob.. hope you are doing well, i wanted to find out if this setup still valid? because. im news to elastic stack so I tried setting this up but kept getting errors related to Suricata indexing in kibana dashboards. This is a really really useful tool and I wanted to use this for my honor's research paper stats. your assistance would be highly appreciated

Best Regards

**Comment by robcowart** [comment]
This solution doesn't support more recent version of the Elastic Stack. You need to stick to 7.1.x.

**Comment by NPascar** [comment]
So there is no way i set it up with latest version elastic stack? I would realy like to set it up for my project.

**Comment by robcowart** [comment]
No there isn't. There have been breaking changes in the Elastic Stack that would require modifications to this project. I simply have no time to work on it. I also have been moving away from Logstash and would rather develop something completely new that replaces both Filebeat and Logstash for this use-case.
