### ISSUE TITLE
Elasticsearch Index Templates incompatible with ES 7.x

### ISSUE THREAD

**Issue by mrplow87** [robcowart/synesis_lite_suricata#9]
The import of the Elasticsearch index templates by Logstash is incompatible with Elasticsearch 7.x, since they removed mapping types:

https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

```
curl -X PUT http://127.0.0.1:9200/_template/synlite-suricata-1.0.1 -H "Content-Type: application/json" -H "kbn-xsrf: true" -d @synlite_suricata.template.json 

{"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"Root mapping definition has unsupported parameters:  [_default_ : {numeric_detection=true, 
```

**Comment by robcowart** [comment]
Yes. Elastic Stack 7.x support will be coming in the next week or two.

**Comment by robcowart** [comment]
[Release v1.1.0](https://github.com/robcowart/synesis_lite_suricata/releases/tag/v1.1.0) is now available for Elastic Stack 7.x.
